"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import Link from "next/link";
import { Send, Phone } from "lucide-react";
import Navbar from "@/components/Navbar";

export default function SupportChatPage() {
  const [messages, setMessages] = useState([
    {
      from: "agent",
      text: "Hi, I’m Riya from MitrAI support 🌱\nI’m here to help you.\nWhat’s been troubling you?"
    }
  ]);
  const [input, setInput] = useState("");
  const agentAvailable = true;

  const sendMessage = () => {
    if (!input.trim()) return;
    setMessages([...messages, { from: "user", text: input }]);
    setInput("");
  };

  return (
    <>
      <Navbar />

      <main className="min-h-screen bg-gradient-to-br from-sky-100 via-blue-50 to-indigo-100 px-4 py-16">
        <div className="max-w-3xl mx-auto bg-white/80 backdrop-blur-xl 
          rounded-3xl shadow-lg border border-white/50 overflow-hidden">

          {/* ===== Header ===== */}
          <div className="p-6 border-b bg-white/70">
            <div className="flex items-center justify-between">
              <Link
                href="/settings/support"
                className="text-indigo-700 font-medium"
              >
                ← Back to Support
              </Link>

              <span className="text-sm flex items-center gap-2 text-gray-800">
                <span
                  className={`w-2 h-2 rounded-full ${
                    agentAvailable ? "bg-green-500" : "bg-yellow-500"
                  }`}
                />
                {agentAvailable
                  ? "Agent available"
                  : "Agent will reply soon"}
              </span>
            </div>

            <p className="text-gray-800 text-sm mt-2">
              You’re chatting with a <strong>human support agent</strong>.
            </p>
          </div>

          {/* ===== Chat Window ===== */}
          <div className="p-6 space-y-4 h-[420px] overflow-y-auto">
            {messages.map((msg, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className={`max-w-[80%] p-4 rounded-2xl text-sm leading-relaxed ${
                  msg.from === "user"
                    ? "ml-auto bg-indigo-500 text-white"
                    : "mr-auto bg-gray-100 text-gray-900"
                }`}
              >
                {msg.text}
              </motion.div>
            ))}

            {agentAvailable && (
              <p className="text-xs text-gray-800">
                This is an autogenerated message. Our agent will respond shortly.
              </p>
            )}

            {!agentAvailable && (
              <p className="text-sm text-gray-800">
                Our support team is currently offline. You can leave a message.
              </p>
            )}
          </div>

          {/* ===== Input Area ===== */}
          <div className="p-4 border-t bg-white/70">
            <div className="flex items-center gap-3">
              <input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Type your message…"
                maxLength={500}
                className="flex-1 px-4 py-3 rounded-full border 
                border-gray-300 text-gray-900 placeholder-gray-600 focus:outline-none"
              />
              <button
                onClick={sendMessage}
                className="p-3 rounded-full bg-indigo-500 
                text-white hover:bg-indigo-600 transition"
              >
                <Send size={18} />
              </button>
            </div>

            <p className="text-xs text-gray-800 mt-2">
              Max 500 characters
            </p>
          </div>

          {/* ===== Emergency Escape ===== */}
          <div className="p-4 bg-yellow-50 border-t text-center">
            <p className="text-sm text-gray-900 mb-2">
              Feeling unsafe right now?
            </p>
            <a
              href="tel:18005990019"
              className="inline-flex items-center gap-2 
              text-indigo-700 font-semibold"
            >
              <Phone size={16} />
              Get immediate help
            </a>
          </div>
        </div>
      </main>
    </>
  );
}
